spring:
  config:
    import:
      - configurations/develop/db-develop-configuration.yml
      - configurations/develop/develop-configuration.yml
      - configurations/kafka-topics/device-kafka-topics.yml
      - configurations/pattern/cors-configuration.yml
      - configurations/pattern/cqrs-configuration.yml
      - configurations/pattern/saga-configuration.yml
      - configurations/actuator-general-configuration.yml
      - configurations/db-configuration.yml
      - configurations/kafka-general-configuration.yml
server:
  port: 8020
db:
  h2:
    debug:
      port: 11001
