spring:
  config:
    import:
      - configurations/develop/develop-configuration.yml
      - configurations/kafka-topics/inventory-kafka-topics.yml
      - configurations/pattern/cors-configuration.yml
      - configurations/pattern/cqrs-configuration.yml
      - configurations/actuator-general-configuration.yml
      - configurations/db-configuration.yml
      - configurations/kafka-general-configuration.yml
server:
  port: 8010
db:
  h2:
    debug:
      port: 11000
resilience4j:
  timelimiter:
    configs:
      defaults:
        timeout-duration: 5s
        cancel-running-future: false
