spring:
  cloud:
    config:
      import:
        - configuration/develop/develop-configuration.yml
        - configuration/kafka-topics/inventory-kafka-topics.yml
        - configuration/pattern/cors-configuration.yml
        - configuration/pattern/cqrs-configuration.yml
        - configuration/actuator-general-configuration.yml
        - configuration/db-configuration.yml
        - configuration/kafka-general-configuration.yml
server:
  port: 8010
db:
  h2:
    debug:
      port: 11000
resilience4j:
  timelimiter:
    configs:
      defaults:
        timeout-duration: 5s
        cancel-running-future: false
