spring:
  config:
    import:
      - configurations/develop/develop-configuration.yml
      - configurations/pattern/cors-configuration.yml
      - configurations/actuator-general-configuration.yml
server:
  port: 8080
service:
  gateway:
    url: ${SERVICE_GATEWAY_URL:http://localhost:8010}
