spring:
  config:
    import:
      - configurations/develop/develop-configuration.yml
      - configurations/pattern/cors-configuration.yml
      - configurations/actuator-general-configuration.yml
server:
  port: 8080
