spring:
  config:
    import:
      - configurations/develop/develop-configuration.yml
      - configurations/kafka-topics/inventory-kafka-topics.yml
      - configurations/pattern/cors-configuration.yml
      - configurations/pattern/cqrs-configuration.yml
      - configurations/actuator-general-configuration.yml
      - configurations/db-configuration.yml
      - configurations/kafka-general-configuration.yml
server:
  port: 8021
db:
  h2:
    debug:
      port: 11002
