spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    hikari:
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 2
      minimum-idle: 2
    url: jdbc:h2:mem:DeviceDB
    username: demo
    password:
    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 4
