kafka:
  enabled: true
  bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
#  bootstrap-servers: ${KAFKA_URL:http://host.docker.internal:29092}
  trust-package: org.alsjava.microservice.*
  timeout: 60000
  retry:
    interval: 5000
    max_attempts: 4
